runtime: nodejs10

steps:
# Install
- name: 'node:10.16.0'
  args: ['install']
# Test
#- name: 'node:10.16.0'
#  args: ['run', 'test:unit']
# Build
- name: 'node:10.16.0'
  args: ['run', 'build']

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build